#!/bin/sh
source /etc/openvpn/peizhi.cfg


echo  $(date +%Y年%m月%d日%k时%M分)读取设定值:"$shijian","$shijian","$chu","$chu2","$localhost","$root","$mima","$shujuku","$users","$user","$isent","$irecv","$maxll","$phone"

if [ -f /etc/openvpn/peizhi.cfg ];
then
jiaobenpath=$(cd `dirname $0`; pwd)
rm -rf ${jiaobenpath}/aa
rm -rf ${jiaobenpath}/bb
rm -rf ${jiaobenpath}/cc
rm -rf ${jiaobenpath}/dd
rm -rf ${jiaobenpath}/gg
echo  $(date +%Y年%m月%d日%k时%M分)正在清除缓存文件
echo  $(date +%Y年%m月%d日%k时%M分)开始执行变脸狗BLDOG监控,当前设定数据监测时间为:"$shijian"秒
bmd5=$(md5sum $jiaobenpath/openvpn-status.log)
while true
do
amd5=$(md5sum $jiaobenpath/openvpn-status.log)
#echo bb="$bmd5"
if [ "$amd5" = "$bmd5" ];
then
amd5=$amd5
else
awk -F: '$1~/[B][y][t][e][s][ ][R][e][c][e][i][v][e][d][,][B][y][t][e][s][ ][S][e][n][t]/,/[R][O][U][T][I][N][G][ ][T][A][B][L][E]/{print $0}' ''$jiaobenpath''/openvpn-status.log | awk -F"," '{print $1 >"'$jiaobenpath'/aa"}'
awk -F: '$1~/[B][y][t][e][s][ ][R][e][c][e][i][v][e][d][,][B][y][t][e][s][ ][S][e][n][t]/,/[R][O][U][T][I][N][G][ ][T][A][B][L][E]/{print $0}' ''$jiaobenpath''/openvpn-status.log | awk -F"," '{print $2 }' | awk -F":" '{print $2 >"'$jiaobenpath'/bb"}'
awk -F: '$1~/[B][y][t][e][s][ ][R][e][c][e][i][v][e][d][,][B][y][t][e][s][ ][S][e][n][t]/,/[R][O][U][T][I][N][G][ ][T][A][B][L][E]/{print $0}' ''$jiaobenpath''/openvpn-status.log | awk -F"," '{print $3 >"'$jiaobenpath'/cc"}'
awk -F: '$1~/[B][y][t][e][s][ ][R][e][c][e][i][v][e][d][,][B][y][t][e][s][ ][S][e][n][t]/,/[R][O][U][T][I][N][G][ ][T][A][B][L][E]/{print $0}' ''$jiaobenpath''/openvpn-status.log | awk -F"," '{print $4 >"'$jiaobenpath'/dd"}'
i=2
until [ $i = -1 ]
do


aaa=$(sed -n ${i}p ${jiaobenpath}/aa)
bbb=$(sed -n ${i}p ${jiaobenpath}/bb)
ccc=$(sed -n ${i}p ${jiaobenpath}/cc)
ddd=$(sed -n ${i}p ${jiaobenpath}/dd)

if [ ! -n "$bbb" ];
then

i=-1

else


mysql -h$localhost -u$root -p$mima -e "use $shujuku;SELECT $isent FROM $users WHERE $user='$aaa';">>${jiaobenpath}/gg
sleep 1
mysql -h$localhost -u$root -p$mima -e "use $shujuku;SELECT $irecv FROM $users WHERE $user='$aaa';">>${jiaobenpath}/gg
sleep 1
mysql -h$localhost -u$root -p$mima -e "use $shujuku;SELECT $maxll FROM $users WHERE $user='$aaa';">>${jiaobenpath}/gg
sleep 1

sent=$(sed -n 2p ${jiaobenpath}/gg)
recv=$(sed -n 4p ${jiaobenpath}/gg)
all=$(sed -n 6p ${jiaobenpath}/gg)
rm -rf ${jiaobenpath}/gg

let sent=$sent/$chuu
let recv=$recv/$chuu
let ccc=$ccc/$chu
let ddd=$ddd/$chu
let cccc=$sent+$ccc
let dddd=$recv+$ddd
let ggg=$cccc+$dddd


#mysql -h$localhost -u$root -p$mima -e "use $shujuku;UPDATE $users SET $isent = '$cccc' WHERE $user='$aaa';"
#sleep 1
#mysql -h$localhost -u$root -p$mima -e "use $shujuku;UPDATE $users SET $irecv = '$dddd' WHERE $user='$aaa';"
#sleep 1
#phones=NULL
if [ "$phone" = "$phones" ];
then
phones=NULL
sleep 1
else
#mysql -h$localhost -u$root -p$mima -e "use $shujuku;UPDATE $users SET $phone = '$ggg' WHERE $user='$aaa';"
sleep 1
fi
if [ "$all" -lt "$ggg"  ];
then
${jiaobenpath}/sha $aaa
sleep 1
echo  $(date +%Y年%m月%d日%k时%M分)成功清理超出流量用户:"$aaa "
fi
i=$(( $i + 1 ))
fi
done
#echo $i
rm -rf ${jiaobenpath}/aa
rm -rf ${jiaobenpath}/bb
rm -rf ${jiaobenpath}/cc
rm -rf ${jiaobenpath}/dd
sleep 1
fi
bmd5=$(md5sum $jiaobenpath/openvpn-status.log)
#echo bb="$bmd5"
sleep 2
sleep $shijian
done
else
echo 读取配置文件失败,请检查.
fi